### ISSUE TITLE
Invalid file due to empty track

### ISSUE THREAD

**Issue by buraksenkus** [cainky/midigen#24]
**Describe the bug**
First of all, I cloned master branch, installed all dependencies and all tests were successful. When I run the `example.py` script, a 26-byte midi file `rnb_progression.mid` was created. Even if I play this MIDI file in several applications (e.g. VLC and Videos app in Ubuntu) there was no sound.

Then, I inspected **midigen** instance and its track(s). I saw that there is no valid data in **_midi_file**'s track content. All content is just stored in midigen's **_track** variable. When I save **_track**'s content into the file, a 173-byte file was created with a valid sound. See Figure 2 for comparison of two files.

**To Reproduce**
1. Add a breakpoint to `midigen.py:316`.
2. Run `python3 ./example.py` in debug mode.
3. See **merged_track** of **midi_file** variable which has no valid note data. See Figure 1 for further details.

**Expected behavior**
With the inspection on `midigen.py`, I would expect that **_midi_file**'s content should be same as the **_track**'s content. And output file of `example.py` script should have a valid melody.

**Screenshots**
Figure 1
![image](https://github.com/cainky/midigen/assets/19664856/bb7658b8-861b-4021-9825-393bb24a1f78)

Figure 2
![image](https://github.com/cainky/midigen/assets/19664856/057bea99-c0aa-4a07-901b-394a4bf2639b)

**Desktop:**
 - OS: Ubuntu 22.04

**Additional context**
I will open a pull request which contains a fix for this issue. After your confirmation on this issue (whether I did anything missing or this is an actual bug) please review my pull request.

Thanks for creating this library. I'm planning to contribute it periodically since I want to use it in one of my personal projects.

**Comment by cainky** [comment]
Thank you for your detailed report on the issue you encountered. Your effort is greatly appreciated. Ultimately our goal is to add multiple track support so it looks to me its most likely a bug leftover due to the implementation only being half finished. I have no issue with merging your changes especially if its working for you now, and I will continue the implementation to add multiple tracks :)
